# Generated by Django 4.1 on 2024-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
