# Generated by Django 4.1 on 2024-04-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_audio_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Podcast',
        ),
    ]
