# Generated by Django 4.1 on 2024-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_post_podcast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcast',
            new_name='Post',
        ),
    ]
